name: jenkins
services:
    jenkins-agent-python:
        image: docker-agent-python
        container_name: docker-agent-python
        restart: unless-stopped
        depends_on:
            - jenkins
        environment:
            - JENKINS_URL=http://jenkins:8080
            - JENKINS_SECRET=8dc73636f3255eadec6d71e3dd33aea12268a4f8e93ce89ecb457877e91bf93b  
            - JENKINS_AGENT_NAME=docker-agent-python
            - JENKINS_AGENT_WORKDIR=/home/jenkins
        volumes:
            - /var/run/docker.sock:/var/run.docker.sock

    jenkins-agent-python-test:
        image: docker-agent-python-test
        container_name: docker-agent-python-test
        restart: unless-stopped
        depends_on:
            - jenkins
        environment:
            - JENKINS_URL=http://jenkins:8080
            - JENKINS_SECRET=62a4a0b9db56267e69fad24f1ad1e4695b9db1a9fc43fd0f00c3d2cfdcebfff5   
            - JENKINS_AGENT_NAME=docker-agent-python-test
            - JENKINS_AGENT_WORKDIR=/home/jenkins
        volumes:
            - /var/run/docker.sock:/var/run.docker.sock

    jenkins:
        image: jenkins/jenkins:latest 
        container_name: jenkins
        ports:
            - "8090:8080"
            - "50000:50000"
        volumes: 
            - C:\Users\quent\Desktop\Ynov\M2\cicd\jenkins:/var/jenkins_home
        restart: unless-stopped
        user: root
        environment:
            - JAVA_OPTS=-Djenkins.install.runSetupWizard=false